[server]
headless = true
enableCORS = false

[client]
toolbarMode = "minimal"
showSidebarNavigation = false
showErrorDetails = false

[theme]
base = "light"
primaryColor = "#004080"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#000000"
font = "sans serif"